#ifndef MESSAGE_TYPE_H
#define MESSAGE_TYPE_H

enum Message
{
	CLIENT_IMAGE_FRAME = 10,
	CLIENT_AUDIO_FRAME = 11,
	REQUEST_IMAGE_STREAM = 12,
	CONFERENCE_IMAGE_FRAME = 13,
	CONFERENCE_AUDIO_FRAME = 14
};

#endif