#ifndef MESSAGE_TYPE_H
#define MESSAGE_TYPE_H

enum Message
{
	CLIENT_IMAGE_FRAME = 10,
	CLIENT_AUDIO_FRAME = 11,
	REQUEST_IMAGE_STREAM = 12,
	REQUEST_AUDIO_STREAM = 13,
	CONFERENCE_IMAGE_FRAME = 14,
	CONFERENCE_AUDIO_FRAME = 15,
	ACCESS_DENIED = 17
};

#endif